export const dynamic = "force-dynamic";

import "./globals.css";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
// components
import MainNav from "../components/MainNav";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = createServerComponentClient({ cookies });
  const { data } = await supabase.auth.getSession();

  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-gradient-body pt-[10vh] mx-auto">
        <MainNav session={data.session} />
        {children}
        <Toaster duration={1000} />
      </body>
    </html>
  );
}
